# ~/.zshrc

##############################
# ZPROF STARTUP TIME PROFILING
##############################
# See https://www.dotruby.com/articles/profiling-zsh-setup-with-zprof
# To profile your .zshrc script and print a summary of all the commands run during your shell startup 
# and the time it takes to execute them, run this: `time ZSH_DEBUGRC=1 zsh -i -c exit`

if [[ -n "$ZSH_DEBUGRC" ]]; then
  zmodload zsh/zprof
fi



########
# SDKMAN
########
# according to sdkman, this should be at the bottom of the file, 
# but there are other configs that must go to the bottom more urgently.
export SDKMAN_DIR="$HOME/.sdkman"
source "$SDKMAN_DIR/bin/sdkman-init.sh" 


###############
# MISCELLANEOUS
###############
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
source ~/.dasch-passwords
export HOWDOI_SEARCH_ENGINE=duckduckgo
source /Users/nussbaum/.pluckeye.homebrew.env
# Homebrew prefers its own curl, installed at /usr/local/bin/curl, but that one doesn't exist.
export HOMEBREW_CURL_PATH=/usr/bin/curl 
source ~/.zsh_aliases


###############
# POWERLEVEL10K
###############
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then # -r: file is readable
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" # %n: name of current shell (zsh-specific)
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh  # -f: is regular file (not directory/socket/...)




###########
# OH-MY-ZSH
###########

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git z zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"



########
# PYTHON
########
export PIP_REQUIRE_VIRTUALENV=true

python_venv() {
  [[ -d .venv ]] && source .venv/bin/activate > /dev/null 2>&1
  [[ ! -d .venv ]] && deactivate > /dev/null 2>&1
}
autoload -U add-zsh-hook
add-zsh-hook chpwd python_venv
python_venv



#######
# PYENV
#######
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"



########
# ZOXIDE
########
# https://github.com/ajeetdsouza/zoxide
function cd() {
    __zoxide_z "$@"
}

function cdi() {
    __zoxide_zi "$@"
}

eval "$(zoxide init zsh)"



#####
# fzf
#####
source <(fzf --zsh)
export FZF_DEFAULT_COMMAND="fd --strip-cwd-prefix --exclude .git --hidden"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# Open in tmux popup if on tmux, otherwise use --height mode
export FZF_DEFAULT_OPTS="--height 40% --tmux bottom,40% --layout reverse --border top --bind 'ctrl-a:reload:eval $FZF_DEFAULT_COMMAND --no-ignore'"



########################
# Docker CLI completions
########################
fpath=(/Users/nussbaum/.docker/completions $fpath)
autoload -Uz compinit
compinit



######
# PNPM
######
export PNPM_HOME="/Users/nussbaum/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end



#######
# ATUIN 
#######
# . "$HOME/.atuin/bin/env"
# eval "$(atuin init zsh --disable-up-arrow)"



#####################################
# ZSH PLUGIN: ZSH-SYNTAX-HIGHLIGHTING
#####################################
# 3rd party plugin, installed with Homebrew, not via Oh My Zsh
# This must be sourced (and register its hook) after anything else that adds hooks that modify the command-line buffer.  
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh



##############################
# ZPROF STARTUP TIME PROFILING
##############################
# See https://www.dotruby.com/articles/profiling-zsh-setup-with-zprof
if [[ -n "$ZSH_DEBUGRC" ]]; then
  zprof
fi

